INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('DHIS Name','EHR Name',get_test_from_test_name('EHR Name'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Hb','Haemoglobin blood',get_test_from_test_name('Haemoglobin blood'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('RBC','RBC count',get_test_from_test_name('RBC count'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Platelates','Platelates',get_test_from_test_name('Platelates'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('WBC','Total Leucocyte count',get_test_from_test_name('Total Leucocyte count'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('DLC','Neutrophil',get_test_from_test_name('Neutrophil'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('ESR','ESR(blood)',get_test_from_test_name('ESR(blood)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('PCV','PCV(blood)',get_test_from_test_name('PCV(blood)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('MCV','MCV',get_test_from_test_name('MCV'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('MCHC/MCH','MCHC',get_test_from_test_name('MCHC'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('BT','Bleeding time',get_test_from_test_name('Bleeding time'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CT','Clotting time',get_test_from_test_name('Clotting time'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Retics','Reticulosite count',get_test_from_test_name('Reticulosite count'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('PBS','PBS for malaria',get_test_from_test_name('PBS for malaria'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('APTT','APTT',get_test_from_test_name('APTT'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Pt-INR','PT INR',get_test_from_test_name('PT INR'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Blood group','blood group',get_test_from_test_name('blood group'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('MP total','PBS for malaria',get_test_from_test_name('PBS for malaria'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('HbA1c','HbA1c',get_test_from_test_name('HbA1c'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Pregnancy test','Urine Pregnancy Test',get_test_from_test_name('Urine Pregnancy Test'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('ASO','ASO',get_test_from_test_name('ASO'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CRP','CRP + CRP(Nephelometry)',get_test_from_test_name('CRP + CRP(Nephelometry)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('RA factor','RA + RF(Nephelometry)',get_test_from_test_name('RA + RF(Nephelometry)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('TPHA','VDRL(TPHA) (Serum) + VDRL(TPHA) (Blood)',get_test_from_test_name('VDRL(TPHA) (Serum) + VDRL(TPHA) (Blood)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('ANA','ANA',get_test_from_test_name('ANA'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('RPR/VDRL','VDRL(TPHA) (Serum)+VDRL(TPHA)(blood)',get_test_from_test_name('VDRL(TPHA) (Serum)+VDRL(TPHA)(blood)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('B-HCG','Urine Pregnancy Test',get_test_from_test_name('Urine Pregnancy Test'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('RK 39','K-39',get_test_from_test_name('K-39'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('JE','NA',get_test_from_test_name('NA'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Dengue','Dengue',get_test_from_test_name('Dengue'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Rapid MP test','MP Serology',get_test_from_test_name('MP Serology'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Mantoux test','Mantoux Test',get_test_from_test_name('Mantoux Test'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Others','To be added in EHR',get_test_from_test_name('To be added in EHR'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Sugar F','Blood sugar fasting + Glucose(F)',get_test_from_test_name('Blood sugar fasting + Glucose(F)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Sugar PP','Blood sugar PP +Glucose(P.P)',get_test_from_test_name('Blood sugar PP +Glucose(P.P)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('SugarR','Blood sugar random + Glucose(R)',get_test_from_test_name('Blood sugar random + Glucose(R)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('blood urea','Urea',get_test_from_test_name('Urea'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Creatinine','Creatinine',get_test_from_test_name('Creatinine'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Uric acid','Uric acid',get_test_from_test_name('Uric acid'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Albumin','Albumin serum',get_test_from_test_name('Albumin serum'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Total Cholea','Total Cholesterol',get_test_from_test_name('Total Cholesterol'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('HD','HDL',get_test_from_test_name('HDL'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('TG','Triglyceride',get_test_from_test_name('Triglyceride'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('LDL','LDL',get_test_from_test_name('LDL'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Calcium','Calcium',get_test_from_test_name('Calcium'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Amylase','Amylase',get_test_from_test_name('Amylase'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('SGOT/AST','SGOT/AST',get_test_from_test_name('SGOT/AST'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('SGPT/ALT','SGPT/ALT',get_test_from_test_name('SGPT/ALT'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Alk Phos','Alkaline Phosphate',get_test_from_test_name('Alkaline Phosphate'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Billi-T','Bilirubin Total',get_test_from_test_name('Bilirubin Total'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Billi-D','Bilirubin Direct',get_test_from_test_name('Bilirubin Direct'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Sodium(Na)','Sodium',get_test_from_test_name('Sodium'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Potassium','Potassium',get_test_from_test_name('Potassium'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('24 hr protein','24 hour urine protein',get_test_from_test_name('24 hour urine protein'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('others','All ADA tests',get_test_from_test_name('All ADA tests'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('ER','Immuno histro chemestry is not available at BH',get_test_from_test_name('Immuno histro chemestry is not available at BH'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Blood','Culture(blood)',get_test_from_test_name('Culture(blood)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Urine','Culture(urine)',get_test_from_test_name('Culture(urine)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Swab','High Vaginal Swab Culture',get_test_from_test_name('High Vaginal Swab Culture'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Stool','Culture(stool)',get_test_from_test_name('Culture(stool)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Pus','Culture (Pus)',get_test_from_test_name('Culture (Pus)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CSF','Culture(csf)',get_test_from_test_name('Culture(csf)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Sputum AFB','AFB stain (sputum)',get_test_from_test_name('AFB stain (sputum)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Leprosy smear','AFP (slit skin)',get_test_from_test_name('AFP (slit skin)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Widal','Widal Test (Serum)',get_test_from_test_name('Widal Test (Serum)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Fungus','KOH Preparation',get_test_from_test_name('KOH Preparation'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('HIV','HIV (serum)',get_test_from_test_name('HIV (serum)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('HBsAG','HBsAg (Serum)',get_test_from_test_name('HBsAg (Serum)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('HCV','HCV (Serum)',get_test_from_test_name('HCV (Serum)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CD4 count','CD4',get_test_from_test_name('CD4'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('others','Dengue',get_test_from_test_name('Dengue'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Stool RE','Color (stool)',get_test_from_test_name('Color (stool)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Occult blood','Occult Blood Test',get_test_from_test_name('Occult Blood Test'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Urine RE','Color (urine)',get_test_from_test_name('Color (urine)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Bile salts','Bile Salt (Urine)',get_test_from_test_name('Bile Salt (Urine)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Bile pigment','Bile pigment',get_test_from_test_name('Bile pigment'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Urobi-linogen','Urobilinogen (Urine)',get_test_from_test_name('Urobilinogen (Urine)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Ace-tone','Ketone Bodies',get_test_from_test_name('Ketone Bodies'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Chyle','Chyle',get_test_from_test_name('Chyle'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('Semen-analysis','Color(semen)',get_test_from_test_name('Color(semen)'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CPK-MB','CP-MB',get_test_from_test_name('CP-MB'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('CPK-NAC','CPK-NAC + CK-NAC',get_test_from_test_name('CPK-NAC + CK-NAC'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('T3','Free T3',get_test_from_test_name('Free T3'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('T4','Free T4',get_test_from_test_name('Free T4'));
INSERT INTO dhis2_lab_test (dhis_test_name, ehr_test_name, ehr_test_id) VALUES('TSH','TSH',get_test_from_test_name('TSH'));
