name: Build and Publish OpenELIS Fresh DB
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

    paths:
      - '.github/workflows/build_publish_openelis_freshDB.yml'
      - 'package/docker/freshDB/**'
      - 'scripts/database/**'
      - 'db_backup/*.sql'

jobs:
  docker-build-publish:
    name: Build & Publish OpenELIS Fresh DB Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: package/docker/freshDB/Dockerfile
          push: true
          tags: bahmni/openelis-db:fresh-${{env.ARTIFACT_VERSION}},bahmni/openelis-db:fresh-latest
